#===============================================================================
# JUCE WebView2 Project Setup Script (Windows PowerShell)
# For schoff_FM and similar JUCE audio plugin projects
#
# Usage:
#   .\setup_webview2.ps1 [-ProjectName "schoff_FM"] [-ProjectPath "C:\Projects\schoff_FM"]
#
# Or just run with defaults:
#   .\setup_webview2.ps1
#===============================================================================

param(
    [string]$ProjectName = "schoff_FM",
    [string]$ProjectPath = "",
    [string]$WebView2Version = "1.0.2535.41"
)

# Set default path if not provided
if ([string]::IsNullOrEmpty($ProjectPath)) {
    $ProjectPath = Join-Path (Get-Location) $ProjectName
}

$ErrorActionPreference = "Stop"

# Colors
function Write-ColorOutput($ForegroundColor) {
    $fc = $host.UI.RawUI.ForegroundColor
    $host.UI.RawUI.ForegroundColor = $ForegroundColor
    if ($args) { Write-Output $args }
    $host.UI.RawUI.ForegroundColor = $fc
}

Write-Host ""
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "JUCE WebView2 Project Setup (Windows)" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Project Name: " -NoNewline; Write-Host $ProjectName -ForegroundColor Green
Write-Host "Project Path: " -NoNewline; Write-Host $ProjectPath -ForegroundColor Green
Write-Host "WebView2 SDK: " -NoNewline; Write-Host $WebView2Version -ForegroundColor Green
Write-Host ""

#===============================================================================
# Step 1: Create Directory Structure
#===============================================================================
Write-Host "[1/5] Creating directory structure..." -ForegroundColor Yellow

New-Item -ItemType Directory -Force -Path $ProjectPath | Out-Null
Set-Location $ProjectPath

$directories = @("Source", "Resources", "Builds", "ThirdParty\WebView2")
foreach ($dir in $directories) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
}

Write-Host "✓ Directory structure created" -ForegroundColor Green

#===============================================================================
# Step 2: Download WebView2 SDK via NuGet
#===============================================================================
Write-Host "[2/5] Downloading WebView2 SDK..." -ForegroundColor Yellow

$webView2Path = "ThirdParty\WebView2\build\native\include\WebView2.h"

if (-not (Test-Path $webView2Path)) {
    $nugetUrl = "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe"
    $nugetPath = "ThirdParty\nuget.exe"
    
    # Download NuGet if needed
    if (-not (Test-Path $nugetPath)) {
        Write-Host "  Downloading NuGet..." -ForegroundColor Gray
        Invoke-WebRequest -Uri $nugetUrl -OutFile $nugetPath
    }
    
    # Download WebView2 SDK
    Write-Host "  Downloading WebView2 SDK $WebView2Version..." -ForegroundColor Gray
    & ".\$nugetPath" install Microsoft.Web.WebView2 -Version $WebView2Version -OutputDirectory "ThirdParty\packages" -NonInteractive
    
    # Move to expected location
    $packagePath = Get-ChildItem "ThirdParty\packages" -Directory | Where-Object { $_.Name -like "Microsoft.Web.WebView2*" } | Select-Object -First 1
    if ($packagePath) {
        Copy-Item "$($packagePath.FullName)\*" "ThirdParty\WebView2\" -Recurse -Force
    }
    
    # Cleanup
    Remove-Item "ThirdParty\packages" -Recurse -Force -ErrorAction SilentlyContinue
    
    Write-Host "✓ WebView2 SDK downloaded and extracted" -ForegroundColor Green
} else {
    Write-Host "✓ WebView2 SDK already present" -ForegroundColor Green
}

#===============================================================================
# Step 3: Create CMakeLists.txt
#===============================================================================
Write-Host "[3/5] Creating CMakeLists.txt..." -ForegroundColor Yellow

$cmakeContent = @"
#===============================================================================
# JUCE 8 WebView2 Plugin - CMake Configuration
# Generated by setup_webview2.ps1
#===============================================================================
cmake_minimum_required(VERSION 3.22)

set(PROJECT_NAME "$ProjectName" CACHE STRING "Plugin name")
set(COMPANY_NAME "9LiveZZZ" CACHE STRING "Company name")
set(PLUGIN_CODE "Schf" CACHE STRING "4-char plugin code")
set(MANUFACTURER_CODE "9Lvz" CACHE STRING "4-char manufacturer code")

project(`${PROJECT_NAME} VERSION 1.0.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Fetch JUCE
include(FetchContent)
FetchContent_Declare(
    JUCE
    GIT_REPOSITORY https://github.com/juce-framework/JUCE.git
    GIT_TAG        8.0.0
    GIT_SHALLOW    TRUE
)
set(JUCE_BUILD_EXTRAS OFF CACHE BOOL "" FORCE)
set(JUCE_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(JUCE)

# WebView2 SDK Path
set(WEBVIEW2_SDK_PATH "`${CMAKE_CURRENT_SOURCE_DIR}/ThirdParty/WebView2" CACHE PATH "WebView2 SDK")

# Create Plugin
juce_add_plugin(`${PROJECT_NAME}
    COMPANY_NAME "`${COMPANY_NAME}"
    IS_SYNTH TRUE
    NEEDS_MIDI_INPUT TRUE
    NEEDS_MIDI_OUTPUT FALSE
    IS_MIDI_EFFECT FALSE
    EDITOR_WANTS_KEYBOARD_FOCUS TRUE
    PLUGIN_MANUFACTURER_CODE `${MANUFACTURER_CODE}
    PLUGIN_CODE `${PLUGIN_CODE}
    FORMATS VST3 Standalone
    PRODUCT_NAME "`${PROJECT_NAME}"
    NEEDS_WEBVIEW2 TRUE
)

target_sources(`${PROJECT_NAME} PRIVATE
    Source/PluginProcessor.cpp
    Source/PluginProcessor.h
    Source/PluginEditor.cpp
    Source/PluginEditor.h
)

target_compile_definitions(`${PROJECT_NAME} PUBLIC
    JUCE_WEB_BROWSER=1
    JUCE_USE_WIN_WEBVIEW2=1
    JUCE_VST3_CAN_REPLACE_VST2=0
    JUCE_DISPLAY_SPLASH_SCREEN=0
    JUCE_USE_CURL=0
)

juce_add_binary_data(`${PROJECT_NAME}_Data
    HEADER_NAME "BinaryData.h"
    NAMESPACE BinaryData
    SOURCES
        Resources/faceplate.html
        Resources/style.css
        Resources/app.js
)

target_link_libraries(`${PROJECT_NAME}
    PRIVATE
        `${PROJECT_NAME}_Data
        juce::juce_audio_basics
        juce::juce_audio_devices
        juce::juce_audio_formats
        juce::juce_audio_plugin_client
        juce::juce_audio_processors
        juce::juce_audio_utils
        juce::juce_core
        juce::juce_data_structures
        juce::juce_events
        juce::juce_graphics
        juce::juce_gui_basics
        juce::juce_gui_extra
    PUBLIC
        juce::juce_recommended_config_flags
        juce::juce_recommended_lto_flags
        juce::juce_recommended_warning_flags
)

if(WIN32)
    target_include_directories(`${PROJECT_NAME} PRIVATE "`${WEBVIEW2_SDK_PATH}/build/native/include")
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(WEBVIEW2_ARCH "x64")
    else()
        set(WEBVIEW2_ARCH "x86")
    endif()
    target_link_directories(`${PROJECT_NAME} PRIVATE "`${WEBVIEW2_SDK_PATH}/build/native/`${WEBVIEW2_ARCH}")
endif()

message(STATUS "")
message(STATUS "==========================================")
message(STATUS "  `${PROJECT_NAME} - WebView2 Enabled")
message(STATUS "==========================================")
"@

$cmakeContent | Out-File -FilePath "CMakeLists.txt" -Encoding UTF8
Write-Host "✓ CMakeLists.txt created" -ForegroundColor Green

#===============================================================================
# Step 4: Create Source Files
#===============================================================================
Write-Host "[4/5] Creating source files..." -ForegroundColor Yellow

# PluginProcessor.h
@"
#pragma once
#include <JuceHeader.h>

class PluginProcessor : public juce::AudioProcessor
{
public:
    PluginProcessor();
    ~PluginProcessor() override;

    void prepareToPlay(double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;
    void processBlock(juce::AudioBuffer<float>&, juce::MidiBuffer&) override;

    juce::AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override { return true; }

    const juce::String getName() const override { return JucePlugin_Name; }
    bool acceptsMidi() const override { return true; }
    bool producesMidi() const override { return false; }
    double getTailLengthSeconds() const override { return 0.0; }

    int getNumPrograms() override { return 1; }
    int getCurrentProgram() override { return 0; }
    void setCurrentProgram(int) override {}
    const juce::String getProgramName(int) override { return {}; }
    void changeProgramName(int, const juce::String&) override {}

    void getStateInformation(juce::MemoryBlock& destData) override;
    void setStateInformation(const void* data, int sizeInBytes) override;

    juce::AudioProcessorValueTreeState& getAPVTS() { return apvts; }

private:
    juce::AudioProcessorValueTreeState apvts;
    juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout();

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(PluginProcessor)
};
"@ | Out-File -FilePath "Source\PluginProcessor.h" -Encoding UTF8

# PluginProcessor.cpp
@"
#include "PluginProcessor.h"
#include "PluginEditor.h"

PluginProcessor::PluginProcessor()
    : AudioProcessor(BusesProperties()
          .withInput("Input", juce::AudioChannelSet::stereo(), true)
          .withOutput("Output", juce::AudioChannelSet::stereo(), true)),
      apvts(*this, nullptr, "Parameters", createParameterLayout())
{
}

PluginProcessor::~PluginProcessor() {}

juce::AudioProcessorValueTreeState::ParameterLayout PluginProcessor::createParameterLayout()
{
    std::vector<std::unique_ptr<juce::RangedAudioParameter>> params;
    
    params.push_back(std::make_unique<juce::AudioParameterFloat>(
        "carrier_freq", "Carrier Frequency",
        juce::NormalisableRange<float>(20.0f, 2000.0f, 0.1f, 0.3f), 440.0f));
    
    params.push_back(std::make_unique<juce::AudioParameterFloat>(
        "mod_index", "Modulation Index",
        juce::NormalisableRange<float>(0.0f, 20.0f, 0.01f), 1.0f));
    
    params.push_back(std::make_unique<juce::AudioParameterFloat>(
        "mod_ratio", "Modulation Ratio",
        juce::NormalisableRange<float>(0.1f, 10.0f, 0.01f), 1.0f));
    
    params.push_back(std::make_unique<juce::AudioParameterFloat>(
        "attack", "Attack",
        juce::NormalisableRange<float>(0.001f, 2.0f, 0.001f, 0.3f), 0.01f));
    
    params.push_back(std::make_unique<juce::AudioParameterFloat>(
        "decay", "Decay",
        juce::NormalisableRange<float>(0.001f, 2.0f, 0.001f, 0.3f), 0.1f));
    
    params.push_back(std::make_unique<juce::AudioParameterFloat>(
        "sustain", "Sustain",
        juce::NormalisableRange<float>(0.0f, 1.0f, 0.01f), 0.7f));
    
    params.push_back(std::make_unique<juce::AudioParameterFloat>(
        "release", "Release",
        juce::NormalisableRange<float>(0.001f, 5.0f, 0.001f, 0.3f), 0.3f));
    
    params.push_back(std::make_unique<juce::AudioParameterFloat>(
        "master_gain", "Master Gain",
        juce::NormalisableRange<float>(-60.0f, 12.0f, 0.1f), 0.0f));
    
    return { params.begin(), params.end() };
}

void PluginProcessor::prepareToPlay(double sampleRate, int samplesPerBlock) {}
void PluginProcessor::releaseResources() {}

void PluginProcessor::processBlock(juce::AudioBuffer<float>& buffer, juce::MidiBuffer& midiMessages)
{
    juce::ScopedNoDenormals noDenormals;
    for (auto i = getTotalNumInputChannels(); i < getTotalNumOutputChannels(); ++i)
        buffer.clear(i, 0, buffer.getNumSamples());
}

juce::AudioProcessorEditor* PluginProcessor::createEditor()
{
    return new PluginEditor(*this);
}

void PluginProcessor::getStateInformation(juce::MemoryBlock& destData)
{
    auto state = apvts.copyState();
    std::unique_ptr<juce::XmlElement> xml(state.createXml());
    copyXmlToBinary(*xml, destData);
}

void PluginProcessor::setStateInformation(const void* data, int sizeInBytes)
{
    std::unique_ptr<juce::XmlElement> xml(getXmlFromBinary(data, sizeInBytes));
    if (xml && xml->hasTagName(apvts.state.getType()))
        apvts.replaceState(juce::ValueTree::fromXml(*xml));
}

juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new PluginProcessor();
}
"@ | Out-File -FilePath "Source\PluginProcessor.cpp" -Encoding UTF8

# PluginEditor.h
@"
#pragma once
#include <JuceHeader.h>
#include "PluginProcessor.h"
#include "BinaryData.h"

class PluginEditor : public juce::AudioProcessorEditor, private juce::Timer
{
public:
    explicit PluginEditor(PluginProcessor&);
    ~PluginEditor() override;

    void paint(juce::Graphics&) override {}
    void resized() override;

private:
    void timerCallback() override;
    std::optional<juce::WebBrowserComponent::Resource> getResource(const juce::String& url);
    
    void handleSetParameter(const juce::Array<juce::var>& args,
                           juce::WebBrowserComponent::NativeFunctionCompletion completion);
    void handleGetParameter(const juce::Array<juce::var>& args,
                           juce::WebBrowserComponent::NativeFunctionCompletion completion);
    void handleGetAllParameters(const juce::Array<juce::var>& args,
                                juce::WebBrowserComponent::NativeFunctionCompletion completion);
    void syncParametersToUI();
    
    PluginProcessor& processor;
    juce::WebBrowserComponent webView;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(PluginEditor)
};
"@ | Out-File -FilePath "Source\PluginEditor.h" -Encoding UTF8

# PluginEditor.cpp
@"
#include "PluginEditor.h"

PluginEditor::PluginEditor(PluginProcessor& p)
    : AudioProcessorEditor(&p),
      processor(p),
      webView(
          juce::WebBrowserComponent::Options{}
              .withBackend(juce::WebBrowserComponent::Options::Backend::webview2)
              .withWinWebView2Options(
                  juce::WebBrowserComponent::Options::WinWebView2{}
                      .withUserDataFolder(
                          juce::File::getSpecialLocation(juce::File::tempDirectory)
                              .getChildFile(JucePlugin_Name "_WebView2"))
                      .withStatusBarDisabled())
              .withNativeFunction("setParameter",
                  [this](auto& args, auto completion) { handleSetParameter(args, std::move(completion)); })
              .withNativeFunction("getParameter",
                  [this](auto& args, auto completion) { handleGetParameter(args, std::move(completion)); })
              .withNativeFunction("getAllParameters",
                  [this](auto& args, auto completion) { handleGetAllParameters(args, std::move(completion)); })
              .withResourceProvider(
                  [this](const juce::String& url) { return getResource(url); },
                  juce::URL("https://plugin.local")))
{
    setSize(800, 600);
    addAndMakeVisible(webView);
    webView.goToURL("https://plugin.local/faceplate.html");
    startTimerHz(30);
}

PluginEditor::~PluginEditor() { stopTimer(); }

void PluginEditor::resized() { webView.setBounds(getLocalBounds()); }

void PluginEditor::timerCallback() { syncParametersToUI(); }

std::optional<juce::WebBrowserComponent::Resource> PluginEditor::getResource(const juce::String& url)
{
    juce::URL parsed(url);
    auto path = parsed.getSubPath();
    if (path.startsWith("/")) path = path.substring(1);
    
    struct ResourceInfo { const char* name; const char* data; int size; const char* mime; };
    const ResourceInfo resources[] = {
        { "faceplate.html", BinaryData::faceplate_html, BinaryData::faceplate_htmlSize, "text/html" },
        { "style.css", BinaryData::style_css, BinaryData::style_cssSize, "text/css" },
        { "app.js", BinaryData::app_js, BinaryData::app_jsSize, "application/javascript" },
    };
    
    for (const auto& r : resources)
        if (path == r.name)
            return juce::WebBrowserComponent::Resource {
                std::vector<std::byte>(reinterpret_cast<const std::byte*>(r.data),
                                       reinterpret_cast<const std::byte*>(r.data) + r.size),
                r.mime };
    return std::nullopt;
}

void PluginEditor::handleSetParameter(const juce::Array<juce::var>& args,
                                       juce::WebBrowserComponent::NativeFunctionCompletion completion)
{
    if (args.size() >= 2) {
        auto id = args[0].toString();
        auto value = static_cast<float>(args[1]);
        if (auto* param = processor.getAPVTS().getParameter(id)) {
            param->setValueNotifyingHost(param->convertTo0to1(value));
            completion(juce::var(true));
            return;
        }
    }
    completion(juce::var(false));
}

void PluginEditor::handleGetParameter(const juce::Array<juce::var>& args,
                                       juce::WebBrowserComponent::NativeFunctionCompletion completion)
{
    if (args.size() >= 1) {
        if (auto* param = processor.getAPVTS().getParameter(args[0].toString())) {
            completion(juce::var(param->getValue()));
            return;
        }
    }
    completion(juce::var());
}

void PluginEditor::handleGetAllParameters(const juce::Array<juce::var>& args,
                                           juce::WebBrowserComponent::NativeFunctionCompletion completion)
{
    juce::DynamicObject::Ptr obj = new juce::DynamicObject();
    for (auto* param : processor.getParameters())
        if (auto* p = dynamic_cast<juce::AudioProcessorParameterWithID*>(param))
            obj->setProperty(p->getParameterID(), param->getValue());
    completion(juce::var(obj.get()));
}

void PluginEditor::syncParametersToUI()
{
    juce::String js = "if(window.updateParams){window.updateParams({";
    bool first = true;
    for (auto* param : processor.getParameters()) {
        if (auto* p = dynamic_cast<juce::AudioProcessorParameterWithID*>(param)) {
            if (!first) js += ",";
            js += "'" + p->getParameterID() + "':" + juce::String(param->getValue());
            first = false;
        }
    }
    js += "});}";
    webView.evaluateJavascript(js, nullptr);
}
"@ | Out-File -FilePath "Source\PluginEditor.cpp" -Encoding UTF8

Write-Host "✓ Source files created" -ForegroundColor Green

#===============================================================================
# Step 5: Create HTML Faceplate Resources
#===============================================================================
Write-Host "[5/5] Creating modern HTML faceplate..." -ForegroundColor Yellow

# faceplate.html
@"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Schoffhauzer FM Synth</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="synth-panel">
        <header class="panel-header">
            <h1>SCHOFFHAUZER</h1>
            <span class="model">FM SYNTHESIZER</span>
        </header>
        
        <section class="control-section">
            <h2>OSCILLATOR</h2>
            <div class="knob-row">
                <div class="knob-group">
                    <div class="knob" data-param="carrier_freq" data-min="20" data-max="2000" data-unit="Hz">
                        <div class="knob-visual"><div class="knob-indicator"></div></div>
                    </div>
                    <label>CARRIER</label>
                    <span class="value-display" id="carrier_freq_display">440 Hz</span>
                </div>
                <div class="knob-group">
                    <div class="knob" data-param="mod_index" data-min="0" data-max="20">
                        <div class="knob-visual"><div class="knob-indicator"></div></div>
                    </div>
                    <label>MOD INDEX</label>
                    <span class="value-display" id="mod_index_display">1.00</span>
                </div>
                <div class="knob-group">
                    <div class="knob" data-param="mod_ratio" data-min="0.1" data-max="10" data-unit=":1">
                        <div class="knob-visual"><div class="knob-indicator"></div></div>
                    </div>
                    <label>MOD RATIO</label>
                    <span class="value-display" id="mod_ratio_display">1.00:1</span>
                </div>
            </div>
        </section>
        
        <section class="control-section">
            <h2>ENVELOPE</h2>
            <div class="knob-row">
                <div class="knob-group">
                    <div class="knob small" data-param="attack" data-min="0.001" data-max="2" data-unit="s">
                        <div class="knob-visual"><div class="knob-indicator"></div></div>
                    </div>
                    <label>A</label>
                    <span class="value-display" id="attack_display">10ms</span>
                </div>
                <div class="knob-group">
                    <div class="knob small" data-param="decay" data-min="0.001" data-max="2" data-unit="s">
                        <div class="knob-visual"><div class="knob-indicator"></div></div>
                    </div>
                    <label>D</label>
                    <span class="value-display" id="decay_display">100ms</span>
                </div>
                <div class="knob-group">
                    <div class="knob small" data-param="sustain" data-min="0" data-max="1">
                        <div class="knob-visual"><div class="knob-indicator"></div></div>
                    </div>
                    <label>S</label>
                    <span class="value-display" id="sustain_display">70%</span>
                </div>
                <div class="knob-group">
                    <div class="knob small" data-param="release" data-min="0.001" data-max="5" data-unit="s">
                        <div class="knob-visual"><div class="knob-indicator"></div></div>
                    </div>
                    <label>R</label>
                    <span class="value-display" id="release_display">300ms</span>
                </div>
            </div>
        </section>
        
        <section class="control-section">
            <h2>OUTPUT</h2>
            <div class="knob-row">
                <div class="knob-group">
                    <div class="knob large" data-param="master_gain" data-min="-60" data-max="12" data-unit="dB">
                        <div class="knob-visual"><div class="knob-indicator"></div></div>
                    </div>
                    <label>MASTER</label>
                    <span class="value-display" id="master_gain_display">0.0 dB</span>
                </div>
            </div>
        </section>
        
        <footer class="panel-footer">
            <span class="brand">9LIVEZZZ</span>
            <span class="version">v1.0</span>
        </footer>
    </div>
    <script type="module" src="app.js"></script>
</body>
</html>
"@ | Out-File -FilePath "Resources\faceplate.html" -Encoding UTF8

# style.css
@"
:root {
    --bg-dark: #1a1a1a;
    --bg-panel: #2d2d2d;
    --bg-section: #252525;
    --accent-primary: #ff6b35;
    --accent-secondary: #00d4aa;
    --text-primary: #e8e8e8;
    --text-secondary: #888;
    --border-color: #444;
    --knob-size: 70px;
    --knob-size-small: 55px;
    --knob-size-large: 90px;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
    font-family: 'Segoe UI', sans-serif;
    background: var(--bg-dark);
    color: var(--text-primary);
    min-height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    user-select: none;
}

.synth-panel {
    background: var(--bg-panel);
    border-radius: 12px;
    padding: 24px;
    box-shadow: 0 20px 60px rgba(0,0,0,0.5);
    border: 1px solid var(--border-color);
    min-width: 700px;
}

.panel-header { text-align: center; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 1px solid var(--border-color); }
.panel-header h1 { font-size: 28px; letter-spacing: 8px; color: var(--accent-primary); }
.panel-header .model { font-size: 11px; letter-spacing: 4px; color: var(--text-secondary); }

.control-section { background: var(--bg-section); border-radius: 8px; padding: 16px; margin-bottom: 16px; }
.control-section h2 { font-size: 10px; letter-spacing: 3px; color: var(--text-secondary); margin-bottom: 16px; }

.knob-row { display: flex; justify-content: center; gap: 32px; flex-wrap: wrap; }
.knob-group { display: flex; flex-direction: column; align-items: center; gap: 8px; }
.knob-group label { font-size: 9px; letter-spacing: 2px; color: var(--text-secondary); }
.value-display { font-size: 11px; font-family: monospace; color: var(--accent-secondary); min-width: 70px; text-align: center; }

.knob { width: var(--knob-size); height: var(--knob-size); cursor: grab; }
.knob.small { width: var(--knob-size-small); height: var(--knob-size-small); }
.knob.large { width: var(--knob-size-large); height: var(--knob-size-large); }
.knob-visual { width: 100%; height: 100%; border-radius: 50%; background: linear-gradient(145deg, #333, #1a1a1a); box-shadow: 4px 4px 8px #111, -2px -2px 6px #444; position: relative; }
.knob-indicator { position: absolute; width: 4px; height: 35%; background: var(--accent-primary); border-radius: 2px; top: 10%; left: 50%; transform: translateX(-50%); box-shadow: 0 0 8px var(--accent-primary); }

.panel-footer { display: flex; justify-content: space-between; padding-top: 16px; border-top: 1px solid var(--border-color); }
.panel-footer span { font-size: 10px; letter-spacing: 3px; color: #555; }
"@ | Out-File -FilePath "Resources\style.css" -Encoding UTF8

# app.js
@"
class SynthUI {
    constructor() {
        this.params = {};
        this.knobs = new Map();
        this.activeKnob = null;
        this.startY = 0;
        this.startValue = 0;
        this.init();
    }
    
    async init() {
        this.mockMode = typeof __JUCE__ === 'undefined';
        await this.loadParameters();
        this.setupKnobs();
        document.addEventListener('mousemove', (e) => this.onMouseMove(e));
        document.addEventListener('mouseup', () => this.onMouseUp());
    }
    
    async loadParameters() {
        if (this.mockMode) {
            this.params = { carrier_freq: 0.21, mod_index: 0.05, mod_ratio: 0.09, attack: 0.005, decay: 0.05, sustain: 0.7, release: 0.06, master_gain: 0.5 };
        } else {
            this.params = await __JUCE__.backend.getNativeFunction('getAllParameters')();
        }
        for (const [id, value] of Object.entries(this.params)) {
            this.updateKnobVisual(id, value);
            this.updateDisplay(id, value);
        }
    }
    
    setupKnobs() {
        document.querySelectorAll('.knob').forEach(el => {
            const id = el.dataset.param;
            this.knobs.set(id, { element: el, min: parseFloat(el.dataset.min) || 0, max: parseFloat(el.dataset.max) || 1, unit: el.dataset.unit || '' });
            if (this.params[id] !== undefined) this.updateKnobVisual(id, this.params[id]);
            el.addEventListener('mousedown', (e) => { e.preventDefault(); this.activeKnob = id; this.startY = e.clientY; this.startValue = this.params[id] || 0; });
            el.addEventListener('dblclick', () => this.setParameter(id, 0.5));
        });
    }
    
    onMouseMove(e) {
        if (!this.activeKnob) return;
        const sensitivity = e.shiftKey ? 0.001 : 0.005;
        let newValue = Math.max(0, Math.min(1, this.startValue + (this.startY - e.clientY) * sensitivity));
        this.setParameter(this.activeKnob, newValue);
    }
    
    onMouseUp() { this.activeKnob = null; }
    
    async setParameter(id, value) {
        this.params[id] = value;
        this.updateKnobVisual(id, value);
        this.updateDisplay(id, value);
        if (!this.mockMode) await __JUCE__.backend.getNativeFunction('setParameter')(id, value);
    }
    
    updateKnobVisual(id, value) {
        const knob = this.knobs.get(id);
        if (knob) knob.element.querySelector('.knob-visual').style.transform = `rotate(${-135 + value * 270}deg)`;
    }
    
    updateDisplay(id, value) {
        const display = document.getElementById(id + '_display');
        const knob = this.knobs.get(id);
        if (!display || !knob) return;
        const real = knob.min + value * (knob.max - knob.min);
        const fmt = { carrier_freq: v => Math.round(v) + ' Hz', mod_index: v => v.toFixed(2), mod_ratio: v => v.toFixed(2) + ':1', attack: v => v < 1 ? Math.round(v*1000) + 'ms' : v.toFixed(2) + 's', decay: v => v < 1 ? Math.round(v*1000) + 'ms' : v.toFixed(2) + 's', sustain: v => Math.round(v*100) + '%', release: v => v < 1 ? Math.round(v*1000) + 'ms' : v.toFixed(2) + 's', master_gain: v => v.toFixed(1) + ' dB' };
        display.textContent = (fmt[id] || (v => v.toFixed(2)))(real);
    }
}

window.updateParams = function(params) {
    if (!window.synthUI) return;
    for (const [id, value] of Object.entries(params)) {
        if (Math.abs((window.synthUI.params[id] || 0) - value) > 0.0001) {
            window.synthUI.params[id] = value;
            window.synthUI.updateKnobVisual(id, value);
            window.synthUI.updateDisplay(id, value);
        }
    }
};

window.synthUI = new SynthUI();
"@ | Out-File -FilePath "Resources\app.js" -Encoding UTF8

Write-Host "✓ Modern HTML faceplate created" -ForegroundColor Green

#===============================================================================
# Done!
#===============================================================================
Write-Host ""
Write-Host "================================================" -ForegroundColor Green
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Project created at: " -NoNewline; Write-Host $ProjectPath -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. cd `"$ProjectPath`""
Write-Host "  2. mkdir build; cd build"
Write-Host "  3. cmake .. -G `"Visual Studio 17 2022`" -A x64"
Write-Host "  4. cmake --build . --config Release"
Write-Host ""
Write-Host "Or open in Visual Studio:" -ForegroundColor Yellow
Write-Host "  cmake .. -G `"Visual Studio 17 2022`" -A x64"
Write-Host "  start $ProjectName.sln"
Write-Host ""
